import './css/materialize.min.css';
import './css/style.css';
import './js/components/footer.js';
import './js/components/navbar.js';
import './js/app.js';
import './js/functions.js';
import './js/register.js';
import './js/materialize.min.js';
import './js/nav.js';